microsoft/WhatTheHack

015-Serverless/Tollbooth/TollBooth/TollBooth.sln, 015-Serverless/Tollbooth/TollBooth/TollBooth/FileMethods.cs, 015-Serverless/Tollbooth/TollBooth/TollBooth/TollBooth.csproj, 015-Serverless/Tollbooth/TollBooth/UploadImagesCore/Program.cs, 015-Serverless/Tollbooth/TollBooth/UploadImagesCore/UploadImagesCore.csproj
Updated the TollBooth application to .NET Core 3.1 to remove some friction during the hack since Functions are now 3.1 by default.
Added a Core version of UploadImages for Mac and Linux users.
=> Updates and new Core uploader

001-IntroToKubernetes/Student/06-deploymongo.md
4/15/21:  Ready for review
Two small changes for Challenge 06:
1. Explicitly direct students to use the MongoDB image on dockerhub.  Reasoning:  This mimics the real world.  You'd never direct a teammate to 'poke around on DockerHub and see what you find, and then use that in production'
2. Call out in a hint that MongoDB runs on port 27017
=> Updates to IntroToKubernetes CH06

038-MDWCovid19/Coach/LabDeployment/deploy/ARM/azuredeploy.parameters.json
I changed the baseUri property to use the ARM templates, scripts, database backups, etc. from the recently-committed WhatTheHack for COVID19.  This will allow me to delete my personal COVID19 repo in the future.
=> Changed baseUri property

021-IdentityForApps/Student/02-susi.md, 021-IdentityForApps/Student/04-l14n.md, 021-IdentityForApps/Student/Resources/HarnessApp/.devcontainer/Dockerfile, 021-IdentityForApps/Student/Resources/HarnessApp/.devcontainer/devcontainer.json, 021-IdentityForApps/Student/Resources/HarnessApp/.devcontainer/library-scripts/azcli-debian.sh, 021-IdentityForApps/Student/Resources/MSGraphApp/.devcontainer/Dockerfile, 021-IdentityForApps/Student/Resources/MSGraphApp/.devcontainer/devcontainer.json, 021-IdentityForApps/Student/Resources/MSGraphApp/.devcontainer/library-scripts/azcli-debian.sh, 021-IdentityForApps/Student/Resources/MSGraphApp/src/Models/AppSettings.cs, 021-IdentityForApps/Student/Resources/MSGraphApp/src/Services/UserService.cs, 021-IdentityForApps/Student/Resources/MSGraphApp/src/appsettings.json, 021-IdentityForApps/Student/Resources/Verify-inator/.devcontainer/Dockerfile, 021-IdentityForApps/Student/Resources/Verify-inator/.devcontainer/devcontainer.json, 021-IdentityForApps/Student/Resources/Verify-inator/.devcontainer/library-scripts/azcli-debian.sh, 021-IdentityForApps/Student/Resources/Verify-inator/tests.http
- added azure cli command to quickly upload blobs in batch so attendees don't lose time on this
- added azure cli command to quickly spin up the harness app in app service so attendees don't lose time on this
- added devcontainers with .NET 3.1 and Azure CLI for:
- harness app
- management app (using graph api to query b2c)
- verify-inator api connector app (contains rest client extension in addition to .net and azure cli)
- added valid http test file for testing api connector with
- make custom user attributes configurable in appsettings.json for MSGraphApp
=> Enhancements to 021 identity for apps

001-IntroToKubernetes/Student/11-opsmonitoring.md
Link to kibana info is broken.  This is a quick fix to that broken link.
Repo owners should feel free to replace with a link to a different documentation page.
=> IntrotoAKS: Quick fix to broken kibana link

001-IntroToKubernetes/Student/Resources/Challenge 7/content-web-v2/public/index.html, 001-IntroToKubernetes/Student/Resources/Challenge 7/content-web-v2/public/sessions.html, 001-IntroToKubernetes/Student/Resources/Challenge 7/content-web-v2/public/speakers.html, 001-IntroToKubernetes/Student/Resources/Challenge 7/content-web-v2/public/stats.html
Fixes #202 :   With V2 of the app, when you are on the home page, it shows the date: 'FEBRUARY 14-17, 2020', but when you go to /sessions or /speakers, it shows the date 'FEBRUARY 14-17, 2019'.
Made a simple correction to the the file \Student\Resources\Challenge 7\content-web-v2\public\index.html
**NOTE:  Content owners will need to rebuild the docker image stored on dockerhub for this change to propagate out to endusers.**
=> IntrotoAKS: change year to 2021 in content-web v2

CODEOWNERS
Allows for sub-management of individual hacks to allow for hack team approval before WTH v-team approval.
=> Create Code Owners File

047-TrafficControlWithDapr/Coach/Solution-02.md
While the pre-reqs section links the correct (local) setup for Dapr, Challange 0 asks participants to run `dapr init -k`.
In Challange 2, we run Dapr locally, hence first it needs to be initialized via `dapr init`.
=> Added `dapr init` to local exec in Solution-02.md

047-TrafficControlWithDapr/Student/Challenge-00.md
publicSSHKey in `Resources/Infrastructure/bicep/main.parameters.json` accepts the public part of the RSA key, which is in `id_rsa.pub` instead of `id_rsa`.
=> Fix RSA input key file

.github/workflows/create-wth-template.sh, 000-HowToHack/WTH-Challenge-Solution-Template.md, 000-HowToHack/WTH-Challenge-Template.md, 000-HowToHack/WTH-CoachGuide-Template.md
This fixes the Coach guide Home links to point to the Coach/README file and adds the hack's title to the titles of the template files
=> fixed README & template files

README.md
Added a link to the WTH website from the homepage of the WTH repo.  This link & message that re-directs students to the WTH Website is embedded in a "Liquid" comment to that Github Pages will not render it on the actual website itself.
=> Wth homepage update

039-AKSEnterpriseGrade/Student/Resources/web/Dockerfile
CentOS Linux 8 had reached the End Of Life (EOL) on December 31st, 2021.
It means that CentOS 8 will no longer receive development resources from the official CentOS project.
After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to
vault.centos.org where they will be archived permanently. Alternatively, you may want to upgrade to CentOS Stream.
Reference: https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
=> [Hack Update] 039-AKSEnterpriseGrade - Fix Centos Dockerfile

033-OSSDatabaseMigration/Student/00-prereqs.md
Prereqs reference migrating Oracle -> Azure DB for Oracle, but should reference Azure DB for PostgreSQL instead.
=> [Hack Update] 033-OSSDatabaseMigration - Update 00-prereqs.md - Issues/Bug

.github/dependabot.yml
Github Actions workflows use runners that are not up to date. Automatic updates can solve this and keep the project up to date in the future.
his PR adds a dependabot file to update the versions of the Github Actions used for CI jobs.
This requires to create a dependabot.yml file and to enable dependabot version updates in the settings of the repository
I applied this to my fork and it proposed the correct updates for the github actions.
https://github.com/iemejia/WhatTheHack/pulls
=> [WTH Core] - chore: Auto update github actions with dependabot

029-IoTEdge/Coach/Challenge-01.md, 029-IoTEdge/Coach/Challenge-03.md, 029-IoTEdge/Coach/Challenge-07.md, 029-IoTEdge/README.md, 029-IoTEdge/Student/Challenge-01.md, 029-IoTEdge/Student/Challenge-02.md, 029-IoTEdge/Student/Challenge-03.md, 029-IoTEdge/Student/Challenge-05.md, 029-IoTEdge/Student/Challenge-06.md
Changes
Main Readme
Added Alan Kleinert as Contributor
Student Challenge 1
Corrected Locations for Device Streams in Challenge 1 (Duplicate Central US to Central US EUAP (Early Updates Access Program)
Fixed broken link for "IoT Edge BackGround Deck" and removed capitalization from the G in BackGround.
Coach Challenge 1
Added additional guidance and references to creating a "virtual" edge device
Student Challenge 2
Removed  "Software ToolBox Top OPC Server" from options for OPC as there are no coaches notes on it and the least favorable option out of the 3
Student Challenge 3
CommandLine link was broken so replaced it with active link
Coach Challenge 3
"Details on container create options" link was broken.  Replaced with new active link.
Added two additional guides to help with OPC …
=> [Hack Update] 029-IoTEdge - 2022 Refresh

README.md
Fixed typo "obsolesence" -> "obsolescence"
=> [WTH Core] Homepage Fix - Typo fix in README.md

.github/workflows/spell-check/.wordlist.txt, 031-DevOpsWithGitHub/Student/Challenge-00.md
Update GitHub challenge00.md to remove Atom and switch to GitHub Codespaces which has been made available free for 60 hours and will reduce friction for Students who are on more restricted corporate devices
=> [Hack Update] 031-DevOpsWithGitHub - Update challenge00.md to remove Atom and switch to Codespaces

015-Serverless/Coach/Solution-05.md
Reporting workaround for WTH 015 Serverless, as there's a bug with upstream code for Azure Functions Core Tools for C#
=> 015-Serverless - point to open bug for Coach instructions

031-DevOpsWithGitHub/Coach/Setup/wth-setup.sh
This pull request includes several updates to the `wth-setup.sh` script to improve consistency and correctness in variable usage, particularly with respect to quoting variables. The changes ensure that variables are correctly interpreted even when they contain special characters or spaces.
Improvements to variable usage:
* Corrected a typo in a comment from "attendeed" to "attended". (`031-DevOpsWithGitHub/Coach/Setup/wth-setup.sh`)
* Added quotes around variables in Azure CLI commands to ensure proper handling of variable values. (`031-DevOpsWithGitHub/Coach/Setup/wth-setup.sh`)
* Ensured that GitHub CLI commands use quoted variables for consistency and to avoid potential issues with variable interpretation. (`031-DevOpsWithGitHub/Coach/Setup/wth-setup.sh`) …
=> [Hack Update] 031-DevOpsWithGitHub - chore: Fix setup script

001-IntroToKubernetes/.wordlist.txt, 001-IntroToKubernetes/Coach/Solution-03.md, 001-IntroToKubernetes/Student/Challenge-03.md
Updated content to reflect that Azure CNI w/ overlay is now the default networking plugin instead of kubenet. This applies to new clusters version 1.30 and higher.
=> update to use cni with overlay as default networking for challenge 3

033-OSSDatabaseMigration/Student/Resources/ARM-Templates/KubernetesCluster/parameters.json, 033-OSSDatabaseMigration/Student/Resources/HelmCharts/MySQL57/values.yaml, 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle184/values.yaml, 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/values.yaml, 033-OSSDatabaseMigration/Student/Resources/HelmCharts/PostgreSQL116/values.yaml
Changed the behavior of the database pods to be internal to the Vnet instead of having an external IP address. Also updated the AKS version to the latest.
=> [Hack Update] 033-OSSDBs - Changed database pods to be internal to VNet and updated AKS version

068-AzureOpenAIApps/README.md
https://github.com/microsoft/WhatTheHack/blob/master/068-AzureOpenAIApps/README.md 
#PingMSFTDocs
=> [Hack Update] 068-AzureOpenAIApps - Update README.md (Typo "Azure Open AI service"→"Azure OpenAI Service")

066-OpenAIFundamentals/Student/Resources/infra/deploy.sh
This pull request introduces a safeguard to the deployment script to prevent accidental overwrites of the `.env` file, along with a minor clarification in a comment. The main improvement is the addition of logic to back up any existing `.env` file before creating a new one.
Environment file handling:
* Added logic to check if the `.env` file exists before creating it; if it does, the script now backs up the existing file with a random suffix to prevent data loss and notifies the user. (`066-OpenAIFundamentals/Student/Resources/infra/deploy.sh`)
Documentation:
* Clarified a comment to specify that the resource group will be created if it does not exist. (`066-OpenAIFundamentals/Student/Resources/infra/deploy.sh`)
=> [HACK UPDATE] 066-Fundamentals of AI - Fix comments and enhance .env file backup logic in deploy script
