- 005-RockPaperScissorsBoom/Student/Guides/challenges/helpers/CreateDockerHostVM.md
A small change to the documentation to make it a tiny bit clearer what the participant needs to do
> Made the directions for creating a docker host a little more explicit

- 010-AzureDevOps/Student/Guides/challenge00.md
- 010-AzureDevOps/Student/Guides/challenge01.md
they changed some stuff on my at build.
> small tweaks

- 012-InfraAsCode-Terraform/Host/Solutions/Challenge 2/Challenge 2 - vnet.tf
- 012-InfraAsCode-Terraform/Host/Solutions/Challenge 4/Challenge 4 - variables.tfvars
- 012-InfraAsCode-Terraform/Host/Solutions/Challenge 5/Challenge 5 - variables.tfvars
- 012-InfraAsCode-Terraform/Host/Solutions/Challenge 6/Challenge 6 - variables.tfvars
Quotes removed from variable names in tfvars files
> Removed quotes from variable names in tfvars files

- 005-RockPaperScissorsBoom/Student/Guides/challenges/RunTheApp.md
- 005-RockPaperScissorsBoom/Student/Guides/challenges/Setup.md
> Two small typos

- 017-FrontDoorCDN/README.md
Reserving a number for Andy's WTH
> Reserving 017 for the Front Door WTH

- 018-BI2AI/README.md
adding a placeholder for the upcoming PowerBI and Azure AI WTH coming from Chris Mitchell & team.
> Reserving 018 for the BI2AI & Beyond WTH!

- 022-AzureGovernance/Coach/readme.md
- 022-AzureGovernance/README.md
Fixed links on hack home page and Coach guide TOC
> 022-AzureGovernance link fix

- 016-AppMigration/Student/Lab2-ContainerizingApplications/src/frontend/package-lock.json
- 016-AppMigration/Student/Lab2-ContainerizingApplications/src/frontend/package.json
- 016-AppMigration/Student/Lab2-ContainerizingApplications/src/product-service/package-lock.json
- 016-AppMigration/Student/Lab2-ContainerizingApplications/src/product-service/package.json
Updates to hopefully remove NPM package deprecation issues
> Appmigration update

- 008-DatabricksIntroML/README.md
The 008 WTH is still in need of a major overhaul.
This is just a fix to a broken link brought to my attention.
> Fixing broken link and minor language.

- 008-DatabricksIntroML/README.md
> Fixing full path of the links to the guide word docs.

- 001-IntroToKubernetes/Coach/01-containers.md
- 001-IntroToKubernetes/Student/Resources/Challenge 1/build-machine/docker-build-machine-config.sh
- 001-IntroToKubernetes/Student/Resources/Challenge 1/build-machine/docker-build-machine-vm.parameters.json
Tested this on my az cli, new VM created and the setup script ran successfully.
> 001 fix broken links in docker machine

- 015-Serverless/Coach/README.md
- 015-Serverless/Student/01-Setup.md
Updated WTH Serverless Setup Prerequisites
> Master: Updated WTH Serverless Setup Prerequisites

- 015-Serverless/Student/05-Deployment.md
add URL on how to crate event grid subscription for Azure function
> Add URL in the resource

- 015-Serverless/Student/04-Configuration.md
As a student, when I trying to configure the first Tast. I got confused. I have assumed the local version of TollBooth project already have application setting json file. And, as first time user of Azure Function, I may not know where to add the application settings for azure function. So I suggest adding the resource for how to do that in the student resources section: https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings
Thanks team.
> Add Application Settings Resource to Task 1

- 030-ConversationalAI/Student/Challenge3-API.md
- 030-ConversationalAI/Student/Challenge4-Deployment.md
I had to update some of the formatting because of how they were being displayed in the UI. In case someone wants to deep dive into these errors, we were seeing visualization problems when we didn't double enter between images and when the character | was used.
> 30-ConversationAI Updated 2 files with small changes needed due to UI irregularities

- README.md
Added a new Section for Teams and put Ed's WTH in there.
> Added new section for the Teams WTH

- 000-HowToHack/WTH-HowToAuthorAHack.md
Updated the presentation links to point to the In-Person and Virtual.
> Update WTH-HowToAuthorAHack.md with correct presentation links.

- 032-MLOpsFromScratch/Coach/README.md
- 032-MLOpsFromScratch/Student/02-BuildPipeline.md
Additionally fixed a broken link based on task 2 and task 3 switch in the readme
> update task 2 goals with removal of a challenge goal

- 001-IntroToKubernetes/Coach/08-storage.md
- 001-IntroToKubernetes/Coach/Solutions/Challenge 8/mongodb-pvc.yaml
- 001-IntroToKubernetes/Coach/Solutions/Challenge 8/storageclass.yaml
- 001-IntroToKubernetes/Student/08-storage.md
- 001-IntroToKubernetes/Student/Resources/Challenge 8/storageclass.yaml
- 001-IntroToKubernetes/Student/Resources/Challenge 8/template-pvc.yaml
4/15/21:  Ready for review
Lots of edits for clarity.
Removed references to the need to create a custom storage class, as this is no longer necessary with AKS.
> Update IntroToKubernetes Ch08 -- Storage

- 001-IntroToKubernetes/Coach/05-scaling.md
- 001-IntroToKubernetes/Student/05-scaling.md
4/15/21:  Ready for review
Student updates:
- Provided link to command for viewing events 
Coach Updates:
- Provided guidance about editing YAML directly in the Azure portal
- Suggestion that coaches demonstrate the AKS autoscaler to students at the end of the challenge
> Updates to IntroToKubernetes CH05

- 001-IntroToKubernetes/Student/07-updaterollback.md
4/15/21:  Ready for review
Minor changes:
- Edits for clarity, including section headings
- Moved details on how to connect to mongodb into the main part of the challenge (it was at the end and easy to miss)
- I added the tips on how to test mongodb into the challenge (eg, connect to the mongodb pod and then run 'show dbs').  These are in the coach's notes, but IMHO we should just provide this info to the students up front.
> Updates to IntroToKubernetes CH07

- 037-WindowsVirtualDesktop/README.md
Updated the README file. Fixed the intro, learning objectives and pre requs.
> Updated README.md

- 001-IntroToKubernetes/Coach/04-k8sdeployment.md
- 001-IntroToKubernetes/Student/04-k8sdeployment.md
minor cleanup of challenge 04.  Added links to documentation.
> Updates to IntroToKubernetes CH04

- 035-HubAndSpoke/README.md
> Fixing bad link

- 001-IntroToKubernetes/Student/Resources/Challenge 1/build-machine/docker-build-machine-vm.json
- 001-IntroToKubernetes/Student/Resources/Challenge 1/build-machine/docker-build-machine-vm.parameters.json
There were issues with Ubuntu 18.04/NPM versions that was leading to a problem when running npm install and obtaining dependencies (underscore).
I've updated both the template and parameters file to use Ubuntu LTS 20.04 from canonical and removed all previous versions.
> Updated OS version for the Linux VM to Ubuntu 20_04 lts

- 037-AzureVirtualDesktop/Student/00-Pre-Reqs.md
**NOTE:** Identity will be used for many aspects - permissions and assignments for example, remember to think about this.**
changed to remove ending **
**NOTE:** Identity will be used for many aspects - permissions and assignments for example, remember to think about this.
> Removed extra ** at end of line 36 for bold

- 031-DevOpsWithGitHub/Student/challenge05.md
dockerFolderPath variable was pointing to wrong directory
The docker login command was missing the login parameter
> fixed login and path

- .github/workflows/checklinks.yml
- .github/workflows/checklinks_config.json
This PR implements a Github actions workflow to automatically validate links within the WTH repo.
At this time, it only validates 001IntroToAKS, but it could be trivially extended to validate the other challenges.
> Create Checklinks action

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/proposal.yml
- .github/ISSUE_TEMPLATE/report.yml
- .github/ISSUE_TEMPLATE/request.yml
- .github/ISSUE_TEMPLATE/suggestion.yml
Add five custom issue templates plus issue template chooser config to require one of these issue templates to be used, not a blank default issue.
> Add custom issue templates

- 019-ThisOldDataWarehouse/Student/Challenges/Challenge4/README.md
Update Challenge 4 to include Streaming on Synapse
> Update Challenge 4 to include Streaming on Synapse

- 001-IntroToKubernetes/Student/11-opsmonitoring.md
Added a more recently updated resource, thank you for your time and consideration.
> Updated an old resource

- 016-AppMigration/Student/Resources/src/frontend/package-lock.json
Updated per github security notification
> Updated Forge Version to 1.0.0

- README.md
Updated Lectures.pptx
- Renamed all references of "Master node" to "Control Plane"
- Added speaker notes for Containers, Container Registry, Container Orchestrator, and Kubernetes Fundamentals sections.
> 001-IntroToKubernetes lecture updates

- README.md
Adding two of our newest hacks to the homepage.
> Added hacks 48 & 49 to the homepage.

- README.md
Listed IntroToAI and DrivingMissData as "archived"
> Adding Linux Fundamentals to the WTH homepage.  

- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge03/C3_2_Concurrency.sql
- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge03/C3_3_Result_Set_Cache_Materialized_View.sql
- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge03/C3_A_Simulate_Writings.ps1
- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge03/C3_B_Simulate_Queries.ps1
- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge03/C3_C_Force_Stop_Queries.ps1
- 049-SQLDedicatedPoolPerf/Coach/Solutions/Challenge04/C4_1_Partitioning_CCI.sql
- 049-SQLDedicatedPoolPerf/Student/Challenge-05.md
- 049-SQLDedicatedPoolPerf/Student/Resources/Challenge-01/C1_2_Create_Actual_Tables.sql
- 049-SQLDedicatedPoolPerf/Student/Resources/Challenge-03/C3_A_Simulate_Writings.ps1
- 049-SQLDedicatedPoolPerf/Student/Resources/Challenge-03/C3_B_Simulate_Queries.ps1
- 049-SQLDedicatedPoolPerf/Student/Resources/Challenge-03/C3_C_Force_Stop_Queries.ps1
Hi,
I'm the content owner, I fixed a bug in 2 powershell scripts and did some minor change to T-SQL scripts
Thanks
Luca
> [Hack Update] 049-SQLDedicatedPoolPerf - Bug fix and minor T-SQL changes

- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/.gitignore
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/README.md
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/database.tf
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/main.tf
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/provider.tf
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/tfvars
- 039-AKSEnterpriseGrade/Coach/Solutions/Terraform/variables.tf
Adding a Terraform solution to the 039-AKSEnterpriseGrade hack. This is really basic and there is room from improvement.
> [Hack Update] 039-AKSEnterpriseGrade provide a Terraform solution

- 023-AdvancedKubernetes/Coach/README.md
Hardcoded URL because it doesn't render properly if clicking link from GH
> [Hack Update] 023-AdvancedKubernetes - Hardcode Coaches slides for AdvK8S

- 035-HubAndSpoke/README.md
Incorrect casing in links to challenges 4 and 5 on readme.md
> [Hack Update] 035-HubAndSpoke - Fix challenge 4 and 5 links on readme.md

- 001-IntroToKubernetes/Coach/Solution-01A.md
- 001-IntroToKubernetes/Coach/Solution-02A.md
- 001-IntroToKubernetes/Coach/Solution-03.md
- 001-IntroToKubernetes/Coach/Solution-04.md
Added links to solution videos
> [HackUpdate] 001-IntroToKubernetes - Dgiard/solution videos

- README.md
Fixed broken links for hack 027 & 044
> [WTH Core] Wth homepage link updates

- 001-IntroToKubernetes/Coach/Solution-05.md
- 001-IntroToKubernetes/Student/Challenge-02A.md
- 001-IntroToKubernetes/Student/Challenge-04.md
- 001-IntroToKubernetes/Student/Challenge-05.md
- 001-IntroToKubernetes/Student/Challenge-08.md
Made some small edits based on some feedback from an Intro AKS WTH Delivery on Dec 12-14
> [Hack Update] 001 IntroToKubernetes - Made some edits based on feedback from Intro to AKS delivery on Dec 12-14

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/report.yml
- .github/ISSUE_TEMPLATE/request.yml
- .github/ISSUE_TEMPLATE/suggestion.yml
Added new WTHs to the combo boxes for all Issues
> [WTH Core] Update combo boxes for all Issues templates with new WTHs

- README.md
Added Bronze-Silver-Gold Using Synapse and Databricks.
> [WTH Core] Add 060 to the homepage

- 000-HowToHack/WTH-HowToHostAHack.md
fixed broken links in host guide
> [WTH Core] Update WTH-HowToHostAHack.md

- 033-OSSDatabaseMigration/Student/Resources/ARM-Templates/KubernetesCluster/parameters.json
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/ContosoPizza/deploy-oracle-pizza.sh
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/ContosoPizza/values-oracle.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/Chart.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/templates/deployment.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/templates/namespace.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/templates/secret.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/templates/service.yaml
- 033-OSSDatabaseMigration/Student/Resources/HelmCharts/Oracle21c/values.yaml
Update for Oracle 21c and for Kubernetes 1.25.5
> [Hack Update] 033-OSSDatabaseMigration - Update for Oracle 21c and for Kubernetes 1.25.5

- .github/actions/spell-check/Dockerfile
- .github/workflows/spell-check/spellcheck.yml
Uses pymdown-extensions, specically pmydownx.superfences
> [WTH Core] - Updated spell checker to ignore code blocks in MD files

- README.md
Fix link to OpenShift hack on home page.
> [WTH Core] - Fix OpenShift hack link

- 015-Serverless/Coach/Solution-03.md
> [Hack Update] 015-Serverless - Update Solution-03.md

- 015-Serverless/.wordlist.txt
- 015-Serverless/Student/Challenge-01.md
- 015-Serverless/Student/Challenge-07.md
- 015-Serverless/Student/Resources/App/UploadImages/Program.cs
- 015-Serverless/Student/Resources/App/UploadImages/UploadImages.csproj
Updated the UploadImages build to net8.0
Also replaced folder references to work with Codespaces (linux relative paths instead of windows paths), and documented in Student guide where to look if that doesn't work in the future
> [015-Serverless] updated challenge 7 to dotnet 8

- 020-LinuxFundamentals/Student/Challenge-03.md
020 linux fundamentals url fix
> 020 linux fundamentals url fix

- README.md
Added 068,070,071,and 069 to the homepage
> [WTH Core] Adding 068,070,071, and 069 to the homepage

- 066-OpenAIFundamentals/Student/Challenge-00.md
updated link to Student REsources.zip in C0
> [Hack Update] 06-OpenAIFundamentals - Updated Resoures.zip 

- 068-AzureOpenAIApps/Coach/SpektraSetup.md
updated link to use published location for setup
> [Hack Update] 068-AzureAIAps - Update SpektraSetup with link to Codespace.md

- .devcontainer/066-OpenAIFundamentals/devcontainer.json
Adding initial devcontainer to test new automation for codespace repo
> Adding initial devcontainer

- 068-AzureOpenAIApps/Student/Resources/infra/checkquota.sh
- 068-AzureOpenAIApps/Student/Resources/infra/quota_check_params.sh
This pull request introduces two new shell scripts to the `068-AzureOpenAIApps/Student/Resources/infra` directory, providing automated checks and reporting for Azure OpenAI quota availability across regions and models. The scripts streamline the process of validating Azure subscription selection, model quota requirements, and region suitability for deployment.
**Quota validation and reporting enhancements:**
* Added `checkquota.sh` to automate checking Azure OpenAI model quotas across specified regions, validate required environment variables, and suggest a region with sufficient quota for deployment. Outputs results to GitHub Actions environment variables for workflow integration.
* Added `quota_check_params.sh` to allow configurable model and region parameters, interactively select …
> [Hack Update] 068-OpenAIApps - Add quota checking scripts for Azure regions and models
